; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

# Build Flags
build_flags = 
    -I include

# Files Filter
# Include or Exclude specific source files from the build process. This is useful for testing, allowing you to compile only the main application code while excluding test files.
build_src_filter = 
    +<*>
    +<main.cpp>  ; Include or Exclude main.cpp from the build, as it will be used for testing only
    -<../test/test_main.cpp>  ; Include or Exclude the test file for main.cpp
    -<../test/test_control_ntc_fans.cpp>  ; Include or Exclude the test file for control_ntc_fans.cpp
    -<../test/test_environmental_sensors.cpp>  ; Include or Exclude the test file for environmental_sensors.cpp
    -<../test/test_first_pcb.cpp>  ; Includer or Exclude the test file for first_pcb.cpp
    -<../test/test_i2c_scanner.cpp>  ; Include or Exclude the test file for i2c_scanner.cpp
    -<../test/test_led_array.cpp>  ; Include or Exclude the test file for led_array.cpp
    -<../test/test_pumps_logic.cpp>  ; Include or Exclude the test file for pumps_logic.cpp
    -<../test/test_ito_glass.cpp> ; Include or Exclude the test file for ito_glass.cpp
    -<../test/test_wifi_communication.cpp>  ; Include or Exclude the test file for wifi_communication.cpp
    
# External Library Dependencies
lib_deps =
    # SHT35 Temperature & Humidity Sensor (I2C)
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    
    # LTR390 UV Light Sensor (I2C)
    adafruit/Adafruit LTR390 Library @ ^1.1.2
    
    # WebSockets for Real-Time Communication
    links2004/WebSockets @ ^2.4.1
    
    # CO2 Sensor T6615-50K 
    # Note: Communicates via UART (Serial2). No external library required, 
    # we will implement the hex command protocol in the Incubator class.

    # PWM Control (LEDs, ITO Glass, Fans)
    # The ESP32 uses the native 'ledc' driver included in the Arduino framework.
    # No extra libraries are needed for PWM functionality.

# Custom Library Directories
lib_extra_dirs = lib

# Test Configuration
# test_build_src = yes